var Skins = {
	a: [
		{
			id: 0,
			position: {x: -6.7, y: Infinity},
			name: "Green Archer",
			gender:	"m",
			projectile:	"arrow",
			projectileAdjust: {x: 20, y: 20},
			cursor: "crosshair",
		},
		{
			id: 1,
			position: {x: -6.7, y: Infinity},
			name: "Blue Archer",
			gender:	"f",
			projectile:	"arrow",
			projectileAdjust: {x: 20, y: 20},
			cursor: "crosshair",
		},
		{
			id: 2,
			position: {x: 20, y: Infinity},
			name: "Jungle Hunter",
			gender:	"m",
			projectile:	"blueBeam",
			projectileAdjust: {x: 20, y: 20},
			cursor: "jungleHunter",
			cursorPosition: {x: 9.5, y: 8},
		},
		{
			id: 3,
			position: {x: Infinity, y: Infinity}, // TBD PG
			name: "Were-Spider",
			gender:	"m",
			projectile:	"arrowOrange",
			projectileAdjust: {x: 20, y: 20},
			cursor: "spooky",
			cursorPosition: {x: 10, y: 10},
		},
	],
	m: [
		{
			id: 0,
			position: {x: -10, y: 20},
			name: "Purple Mage",
			gender:	"m",
			projectile:	"fireball",
			projectileAdjust: {x: 20, y: 20},
			cursor: "crosshair",
		},
		{
			id: 1,
			position: {x: -10, y: 20},
			name: "Blue Mage",
			gender:	"f",
			projectile:	"fireball",
			projectileAdjust: {x: 20, y: 20},
			cursor: "crosshair",
		},
		{
			id: 2,
			position: {x: -20, y: Infinity},
			name: "Spirit Buster",
			gender:	"m",
			projectile:	"spiritbuster",
			projectileAdjust: {x: 0, y: 0},
			cursor: "crosshair",
			animations: {
				onAttack: {
					type: "beam",
					width: 10,
					colour: "#D05C05"
					//gradient: {"0": "#e28909","1": "#e23e09",},
				}
			},
		},
		{
			id: 3,
			position: {x: -20, y: -6.7},
			name: "Wicked Witch",
			gender:	"m",
			projectile:	"fireballGreen",
			projectileAdjust: {x: 20, y: 20},
			cursor: "spooky",
			cursorPosition: {x: 10, y: 10},
		},
	],
	k: [
		{
			id: 0,
			position: {x: -6.7, y: -10},
			name: "Blue Knight",
			gender:	"m",
			projectile:	"slash",
			projectileAdjust: {x: 20, y: 20},
			cursor: "crosshair",
		},
		{
			id: 1,
			position: {x: -6.7, y: -10},
			name: "Red Knight",
			gender:	"f",
			projectile:	"slash",
			projectileAdjust: {x: 20, y: 20},
			cursor: "crosshair",
		},
		{
			id: 2,
			position: {x: -20, y: Infinity},
			name: "Wisconsin Jones",
			gender:	"m",
			projectile:	"slash",
			projectileAdjust: {x: 20, y: 20},
			cursor: "crosshair",
		},
		{
			id: 3,
			position: {x: -6.7, y: 10},
			name: "Animated Scarecrow",
			gender:	"m",
			projectile:	"bloodSlash",
			projectileAdjust: {x: 20, y: 20},
			cursor: "spooky",
			cursorPosition: {x: 10, y: 10},
		},
	],
};