var Skins = {
	a: [
		{
			id: 0,
			position: {x: -6.7, y: Infinity},
			name: "Green Archer",
			gender:	"m",
			projectile:	"arrow",
			cursor: "crosshair",
		},
		{
			id: 1,
			position: {x: -6.7, y: Infinity},
			name: "Blue Archer",
			gender:	"f",
			projectile:	"arrow",
			cursor: "crosshair",
		},
		{
			id: 2,
			position: {x: 20, y: Infinity},
			name: "Jungle Hunter",
			gender:	"m",
			projectile:	"blueBeam",
			cursor: "jungleHunter",
			cursorPosition: {x: 9.5, y: 8},
		},
		/*{
			id: 3,
			position: {x: Infinity, y: Infinity},
			name: "Spider Archer",
			gender:	"m",
			projectile:	undefined,
			cursor: "spooky",
			cursorPosition: {x: 10, y: 10},
		},*/
	],
	m: [
		{
			id: 0,
			position: {x: -10, y: 20},
			name: "Purple Mage",
			gender:	"m",
			projectile:	"fireball",
			cursor: "crosshair",
		},
		{
			id: 1,
			position: {x: -10, y: 20},
			name: "Blue Mage",
			gender:	"f",
			projectile:	"fireball",
			cursor: "crosshair",
		},
		{
			id: 2,
			position: {x: -20, y: Infinity},
			name: "Spirit Buster",
			gender:	"m",
			projectile:	undefined,
			cursor: "crosshair",
		},
		/*{
			id: 3,
			position: {x: -20, y: -6.7},
			name: "Witch",
			gender:	"m",
			projectile:	undefined,
			cursor: "spooky",
			cursorposition: {x: 10, y: 10},
		},*/
	],
	k: [
		{
			id: 0,
			position: {x: -6.7, y: -10},
			name: "Blue Knight",
			gender:	"m",
			projectile:	"slash",
			cursor: "crosshair",
		},
		{
			id: 1,
			position: {x: -6.7, y: -10},
			name: "Red Knight",
			gender:	"f",
			projectile:	"slash",
			cursor: "crosshair",
		},
		{
			id: 2,
			position: {x: -20, y: Infinity},
			name: "Wisconsin Jones",
			gender:	"m",
			projectile:	"slash",
			cursor: "crosshair",
		},
		/*{
			id: 3,
			position: {x: -6.7, y: 10},
			name: "Scarecrow",
			gender:	"m",
			projectile:	undefined,
			cursor: "spooky",
			cursorposition: {x: 10, y: 10},
		},*/
	],
};